name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install poetry and dependencies
      run: |
        python -m pip install --upgrade poetry
        ./build.sh
    - name: Test with pytest
      run: |
        poetry run python -m pytest tests/
